export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

// Alert types
export const SET_MESSAGE = 'SET_MESSAGE'
export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ALERTS = 'CLEAR_ALERTS'

// product types
export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL'

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL'

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL'

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'

// inventory types
export const CREATE_INVENTORY_REQUEST = 'CREATE_INVENTORY_REQUEST'
export const CREATE_INVENTORY_SUCCESS = 'CREATE_INVENTORY_SUCCESS'
export const CREATE_INVENTORY_FAIL = 'CREATE_INVENTORY_FAIL'

export const FETCH_INVENTORY_REQUEST = 'FETCH_INVENTORY_REQUEST'
export const FETCH_INVENTORY_SUCCESS = 'FETCH_INVENTORY_SUCCESS'
export const FETCH_INVENTORY_FAIL = 'FETCH_INVENTORY_FAIL'

export const UPDATE_INVENTORY_REQUEST = 'UPDATE_INVENTORY_REQUEST'
export const UPDATE_INVENTORY_SUCCESS = 'UPDATE_INVENTORY_SUCCESS'
export const UPDATE_INVENTORY_FAIL = 'UPDATE_INVENTORY_FAIL'

// customer types
export const CREATE_CUSTOMER_REQUEST = 'CREATE_CUSTOMER_REQUEST'
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS'
export const CREATE_CUSTOMER_FAIL = 'CREATE_CUSTOMER_FAIL'

export const FETCH_CUSTOMERS_REQUEST = 'FETCH_CUSTOMERS_REQUEST'
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS'
export const FETCH_CUSTOMERS_FAIL = 'FETCH_CUSTOMERS_FAIL'

export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST'
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS'
export const UPDATE_CUSTOMER_FAIL = 'UPDATE_CUSTOMER_FAIL'

export const DELETE_CUSTOMER_REQUEST = 'DELETE_CUSTOMER_REQUEST'
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS'
export const DELETE_CUSTOMER_FAIL = 'DELETE_CUSTOMER_FAIL'

export const CREATE_SALES_REQUEST = 'CREATE_SALES_REQUEST'
export const CREATE_SALES_SUCCESS = 'CREATE_SALES_SUCCESS'
export const CREATE_SALES_FAIL = 'CREATE_SALES_FAIL'

export const FETCH_SALES_REQUEST = 'FETCH_SALES_REQUEST'
export const FETCH_SALES_SUCCESS = 'FETCH_SALES_SUCCESS'
export const FETCH_SALES_FAIL = 'FETCH_SALES_FAIL'

export const FETCH_SALES_BY_NAME_REQUEST = 'FETCH_SALES_BY_NAME_REQUEST'
export const FETCH_SALES_BY_NAME_SUCCESS = 'FETCH_SALES_BY_NAME_SUCCESS'
export const FETCH_SALES_BY_NAME_FAIL = 'FETCH_SALES_BY_NAME_FAIL'

export const UPDATE_SALES_REQUEST = 'UPDATE_SALES_REQUEST'
export const UPDATE_SALES_SUCCESS = 'UPDATE_SALES_SUCCESS'
export const UPDATE_SALES_FAIL = 'UPDATE_SALES_FAIL'

export const DELETE_SALES_REQUEST = 'DELETE_SALES_REQUEST'
export const DELETE_SALES_SUCCESS = 'DELETE_SALES_SUCCESS'
export const DELETE_SALES_FAIL = 'DELETE_SALES_FAIL'
